[package]
name = "envtest"
version = "0.1.0"
edition = "2024"
license = "MIT/Apache-2.0"
include = ["/src", "/go"]

[dependencies]
rust2go = { version = "0.4.1" }
serde = "1"
serde_json = "1"
thiserror = "2"

[build-dependencies]
rust2go = { version = "0.4.1", features = ["build"] }
